apiVersion: v1
data:
  v4-0-config-system-session: eyJraW5kIjoiU2Vzc2lvblNlY3JldHMiLCJhcGlWZXJzaW9uIjoib3BlcmF0b3J2MWNsaWVudCIsInNlY3JldHMiOlt7ImF1dGhlbnRpY2F0aW9uIjoiY2dtemxNeU5WQUhqQ2ZQLVFUWWRGQ0xLM1QyUGdXb2o1cUtTNmJ5N1NNY1U2NlYxcjFzeVd2dUJiRWgzYTJRaCIsImVuY3J5cHRpb24iOiJrTS1ZWXIyR3VJLW9FcGRISVEybXMzekZEaWRaWkFSSSJ9XX0=
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: oauth-openshift
  name: v4-0-config-system-session
  namespace: openshift-authentication
